---
# This Playbook runs all the common plays in the deployment 

- name: Create the hosts file for all machines
  sudo: yes
  template: src=hosts.j2 dest=/etc/hosts

- name: Create the repository for 10Gen
  sudo: yes
  copy: src=10gen.repo.j2 dest=/etc/yum.repos.d/10gen.repo

- name: Create the EPEL Repository.
  sudo: yes
  copy: src=epel.repo.j2 dest=/etc/yum.repos.d/epel.repo

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg

- name: Create the mongod user
  sudo: yes
  user: name=mongod comment="MongoD"

- name: Create the data directory for the namenode metadata
  sudo: yes
  file: path={{ mongodb_datadir_prefix }} owner=mongod group=mongod state=directory

- name: Install the mongodb package
  sudo: yes
  yum: name={{ item }} state=installed
  with_items:
   - libselinux-python
   - mongo-10gen
   - mongo-10gen-server
   - bc
   - python-pip

- name: Install the latest pymongo package
  sudo: yes
  pip: name=pymongo state=latest use_mirrors=no 

- name: Create the iptables file
  sudo: yes
  template: src=iptables.j2 dest=/etc/sysconfig/iptables
#  notify: restart iptables
